name: Package 
on: [push, workflow_dispatch]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.6.1'
      - name: Build
        run: |
          yarn install --frozen-lock-file
          yarn build
          yarn package
      # - name: Upload
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: module-presonus-studiolive.zip
      #     path: module-presonus-studiolive.zip
